sudo: false
language: ruby
rvm:
  - 2.3.3
before_install: gem install bundler -v 1.13.7

deploy:
  on:
    tags: true
  provider: rubygems
  api_key:
    secure: Z4sBUqVeIuNJNKxXa+oYDxnfXlVaCAYl3f+8rWm4pKnHpLQYP1M8vj5LM3cmdHtUQiy/085zkvt5C6p2045PZ5sX3rueojoShqfvmNHgr3wYWQ2MZ3oHy3Vl6UJ3JYGoM/2wEclmqWQ49s1Zk4gnNZR4QyNZ/P4SWZ4FmJ9VmlI=

addons:
  code_climate:
    repo_token: 11e7712330b39d9d748126a0fccccb0dc60f19536ad3d46f2ca484003ff4899c

after_success:
  - bundle exec codeclimate-test-reporter
