require_relative 'application/dispatcher'
require_relative 'application/feature_helper'
require_relative 'application/app_container'
require_relative 'application/root'
require_relative 'application/container_class_registration'
